#!/bin/bash
# ============================================================
#  L2TP/IPsec VPN + Farsi Web Panel  -  one-shot installer
#  Features: per-user traffic quota, time-limit (expiry),
#            single-session, bandwidth shaping, HTTPS panel.
#  Usage:  sudo bash install.sh
# ============================================================
set -e
[ "$(id -u)" -eq 0 ] || { echo "لطفاً با روت (sudo) اجرا کنید"; exit 1; }

echo "==================================================="
echo "        نصب پنل و سرور L2TP VPN"
echo "==================================================="
read -rp "دامنه پنل (مثال l2tp.example.com): " DOMAIN
read -rp "ایمیل برای گواهی SSL: " EMAIL
read -rp "نام کاربری ورود به پنل: " PANEL_USER
read -rsp "رمز عبور ورود به پنل: " PANEL_PASS; echo
read -rp "کلید مشترک IPsec (PSK): " VPN_PSK
read -rp "اولین کاربر VPN (نام کاربری): " V1USER
read -rsp "رمز اولین کاربر VPN: " V1PASS; echo
read -rp "پورت داخلی پنل [8088]: " PANEL_PORT; PANEL_PORT=${PANEL_PORT:-8088}
DL_LIMIT="200mbit"; UL_LIMIT="20mbit"
export DEBIAN_FRONTEND=noninteractive

echo ">> نصب L2TP/IPsec (hwdsl2)..."
wget -qO /tmp/vpnsetup.sh https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup.sh
VPN_IPSEC_PSK="$VPN_PSK" VPN_USER="$V1USER" VPN_PASSWORD="$V1PASS" sh /tmp/vpnsetup.sh >/tmp/vpnsetup.log 2>&1 || true

echo ">> نصب nginx / certbot / ابزارها..."
apt-get update -qq
apt-get -yqq install nginx certbot python3-certbot-nginx iproute2 >/dev/null

echo ">> ساخت مسیرها..."
mkdir -p /var/lib/vpnstat /run/vpn-online /run/vpn-blocked
[ -f /var/lib/vpnstat/usage.json ] || echo "{}" > /var/lib/vpnstat/usage.json
[ -f /var/lib/vpnstat/meta.json ]  || echo "{}" > /var/lib/vpnstat/meta.json

echo ">> اسکریپت محدودیت پهنای‌باند..."
cat > /etc/ppp/ip-up.d/50-ratelimit <<RL
#!/bin/bash
IF="\$1"; [ -z "\$IF" ] && exit 0
tc qdisc del dev "\$IF" root 2>/dev/null
tc qdisc add dev "\$IF" root handle 1: htb default 10
tc class add dev "\$IF" parent 1: classid 1:10 htb rate ${DL_LIMIT} ceil ${DL_LIMIT}
tc qdisc del dev "\$IF" ingress 2>/dev/null
tc qdisc add dev "\$IF" handle ffff: ingress
tc filter add dev "\$IF" parent ffff: protocol ip u32 match u32 0 0 police rate ${UL_LIMIT} burst 200k mtu 64kb drop flowid :1
exit 0
RL
chmod +x /etc/ppp/ip-up.d/50-ratelimit

echo ">> گارد تک‌نشست و بلاک..."
cat > /etc/ppp/ip-up.d/20-vpnguard <<'GUARD'
#!/bin/bash
IF="$1"; USER="$PEERNAME"; PID="$PPID"
[ -z "$USER" ] && exit 0
mkdir -p /run/vpn-online /run/vpn-blocked
[ -f "/run/vpn-blocked/$USER" ] && { kill "$PID" 2>/dev/null; exit 0; }
for f in /run/vpn-online/*; do
  [ -e "$f" ] || continue
  [ "$f" = "/run/vpn-online/$IF" ] && continue
  if [ "$(head -1 "$f")" = "$USER" ]; then
    opid=$(sed -n 2p "$f" | awk "{print \$2}")
    [ -n "$opid" ] && kill "$opid" 2>/dev/null
    rm -f "$f"
  fi
done
printf "%s\n%s %s\n" "$USER" "$(date +%s)" "$PID" > "/run/vpn-online/$IF"
exit 0
GUARD
chmod +x /etc/ppp/ip-up.d/20-vpnguard

echo ">> حساب‌داری مصرف..."
cat > /etc/ppp/ip-down.d/60-acct <<'ACCT'
#!/bin/bash
IF="$1"; USER="$PEERNAME"
[ -z "$USER" ] && [ -f "/run/vpn-online/$IF" ] && USER="$(head -1 /run/vpn-online/$IF)"
[ -z "$USER" ] && exit 0
python3 - "$USER" "${BYTES_RCVD:-0}" "${BYTES_SENT:-0}" <<PY
import json,sys,fcntl
u,rx,tx=sys.argv[1],int(sys.argv[2]),int(sys.argv[3])
p="/var/lib/vpnstat/usage.json"
f=open(p,"a+"); fcntl.flock(f,fcntl.LOCK_EX); f.seek(0)
try: d=json.load(f)
except: d={}
e=d.get(u,{"rx":0,"tx":0}); e["rx"]+=rx; e["tx"]+=tx; d[u]=e
f.seek(0); f.truncate(); json.dump(d,f)
PY
rm -f "/run/vpn-online/$IF"
exit 0
ACCT
chmod +x /etc/ppp/ip-down.d/60-acct

echo ">> بهبود پایداری pppd + MSS clamp..."
sed -i "s/^lcp-echo-interval.*/lcp-echo-interval 20/;s/^lcp-echo-failure.*/lcp-echo-failure 30/" /etc/ppp/options.xl2tpd 2>/dev/null || true
iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -o ppp+ -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -o ppp+ -j TCPMSS --clamp-mss-to-pmtu
iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -i ppp+ -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -i ppp+ -j TCPMSS --clamp-mss-to-pmtu
netfilter-persistent save 2>/dev/null || true

echo ">> نصب پنل..."
echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwojIEwyVFAgVlBOIFBhbmVsIC0gRmFyc2kgVUksIGxvZ2luLCBwZXItdXNlciB0cmFmZmljIHF1b3RhICsgdGltZSBsaW1pdAppbXBvcnQganNvbiwgb3MsIGdsb2IsIHJlLCBzdWJwcm9jZXNzLCB1cmxsaWIucGFyc2UsIHNlY3JldHMsIHRpbWUsIGRhdGV0aW1lCmZyb20gaHR0cC5zZXJ2ZXIgaW1wb3J0IEJhc2VIVFRQUmVxdWVzdEhhbmRsZXIsIEhUVFBTZXJ2ZXIKCiMgPT09PSBDT05GSUcgKGluc3RhbGwuc2ggcmVwbGFjZXMgdGhlc2UpID09PT0KQURNSU5fVVNFUiA9ICJfX1BBTkVMX1VTRVJfXyIKQURNSU5fUEFTUyA9ICJfX1BBTkVMX1BBU1NfXyIKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQpTVE9SRSAgPSAiL3Zhci9saWIvdnBuc3RhdC91c2FnZS5qc29uIgpNRVRBICAgPSAiL3Zhci9saWIvdnBuc3RhdC9tZXRhLmpzb24iCk9OTElORSA9ICIvcnVuL3Zwbi1vbmxpbmUiCkJMT0NLICA9ICIvcnVuL3Zwbi1ibG9ja2VkIgpDSEFQICAgPSAiL2V0Yy9wcHAvY2hhcC1zZWNyZXRzIgpHQiA9IDEwMjQqKjMKU0VTU0lPTlMgPSB7fQoKZGVmIGpsb2FkKHApOgogICAgdHJ5OiByZXR1cm4ganNvbi5sb2FkKG9wZW4ocCkpCiAgICBleGNlcHQgRXhjZXB0aW9uOiByZXR1cm4ge30KZGVmIGpzYXZlKHAsIGQpOiBqc29uLmR1bXAoZCwgb3BlbihwLCAidyIpKQoKZGVmIGxpc3RfdXNlcnMoKToKICAgIHVzID0gW10KICAgIHRyeToKICAgICAgICBmb3IgbG4gaW4gb3BlbihDSEFQKToKICAgICAgICAgICAgbSA9IHJlLm1hdGNoKHInXiIoW14iXSspIlxzK2wydHBkXHMrIihbXiJdKikiJywgbG4uc3RyaXAoKSkKICAgICAgICAgICAgaWYgbTogdXMuYXBwZW5kKChtLmdyb3VwKDEpLCBtLmdyb3VwKDIpKSkKICAgIGV4Y2VwdCBFeGNlcHRpb246IHBhc3MKICAgIHJldHVybiB1cwoKZGVmIGFkZF91c2VyKG5hbWUsIHB3LCBxdW90YV9nYiwgZGF5cyk6CiAgICBuYW1lID0gcmUuc3ViKHInW15BLVphLXowLTlfLi1dJywgJycsIG5hbWUgb3IgIiIpCiAgICBpZiBub3QgbmFtZSBvciBub3QgcHc6IHJldHVybgogICAgbGluZXMgPSBbbCBmb3IgbCBpbiBvcGVuKENIQVApLnJlYWQoKS5zcGxpdGxpbmVzKCkKICAgICAgICAgICAgIGlmIG5vdCByZS5tYXRjaChyJ14iJXMiXHMrbDJ0cGQnICUgcmUuZXNjYXBlKG5hbWUpLCBsLnN0cmlwKCkpXQogICAgbGluZXMuYXBwZW5kKCciJXMiIGwydHBkICIlcyIgKicgJSAobmFtZSwgcHcpKQogICAgb3BlbihDSEFQLCAidyIpLndyaXRlKCJcbiIuam9pbihsaW5lcykgKyAiXG4iKQogICAgbWV0YSA9IGpsb2FkKE1FVEEpCiAgICB0cnk6IHEgPSBpbnQoZmxvYXQocXVvdGFfZ2IpICogR0IpCiAgICBleGNlcHQgRXhjZXB0aW9uOiBxID0gMjAgKiBHQgogICAgdHJ5OiBkID0gaW50KGZsb2F0KGRheXMpKQogICAgZXhjZXB0IEV4Y2VwdGlvbjogZCA9IDAKICAgIGV4cGlyZSA9ICIiIGlmIGQgPD0gMCBlbHNlIChkYXRldGltZS5kYXRlLnRvZGF5KCkgKyBkYXRldGltZS50aW1lZGVsdGEoZGF5cz1kKSkuaXNvZm9ybWF0KCkKICAgIG1ldGFbbmFtZV0gPSB7InF1b3RhIjogcSwgImNyZWF0ZWQiOiB0aW1lLnN0cmZ0aW1lKCIlWS0lbS0lZCIpLCAiZXhwaXJlIjogZXhwaXJlfQogICAganNhdmUoTUVUQSwgbWV0YSkKICAgIHN1YnByb2Nlc3MuY2FsbChbImlwc2VjIiwgImF1dG8iLCAiLS1yZXJlYWRzZWNyZXRzIl0pCgpkZWYgZGVsX3VzZXIobmFtZSk6CiAgICBsaW5lcyA9IFtsIGZvciBsIGluIG9wZW4oQ0hBUCkucmVhZCgpLnNwbGl0bGluZXMoKQogICAgICAgICAgICAgaWYgbm90IHJlLm1hdGNoKHInXiIlcyJccytsMnRwZCcgJSByZS5lc2NhcGUobmFtZSksIGwuc3RyaXAoKSldCiAgICBvcGVuKENIQVAsICJ3Iikud3JpdGUoIlxuIi5qb2luKGxpbmVzKSArICJcbiIpCiAgICBmb3Igc3RvcmUgaW4gKFNUT1JFLCBNRVRBKToKICAgICAgICBkID0gamxvYWQoc3RvcmUpCiAgICAgICAgaWYgbmFtZSBpbiBkOiBkZWwgZFtuYW1lXTsganNhdmUoc3RvcmUsIGQpCiAgICB0cnk6IG9zLnJlbW92ZShCTE9DSyArICIvIiArIG5hbWUpCiAgICBleGNlcHQgRXhjZXB0aW9uOiBwYXNzCiAgICBzdWJwcm9jZXNzLmNhbGwoWyJpcHNlYyIsICJhdXRvIiwgIi0tcmVyZWFkc2VjcmV0cyJdKQoKZGVmIHJlc2V0X3VzYWdlKG5hbWUpOgogICAgZCA9IGpsb2FkKFNUT1JFKQogICAgaWYgbmFtZSBpbiBkOiBkZWwgZFtuYW1lXTsganNhdmUoU1RPUkUsIGQpCiAgICB0cnk6IG9zLnJlbW92ZShCTE9DSyArICIvIiArIG5hbWUpCiAgICBleGNlcHQgRXhjZXB0aW9uOiBwYXNzCgpkZWYgcmVuZXcobmFtZSwgZGF5cyk6CiAgICBtZXRhID0gamxvYWQoTUVUQSkKICAgIGlmIG5hbWUgaW4gbWV0YToKICAgICAgICB0cnk6IGRkID0gaW50KGZsb2F0KGRheXMpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246IGRkID0gMzAKICAgICAgICBiYXNlID0gZGF0ZXRpbWUuZGF0ZS50b2RheSgpCiAgICAgICAgY3VyID0gbWV0YVtuYW1lXS5nZXQoImV4cGlyZSIsICIiKQogICAgICAgIGlmIGN1cjoKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgYyA9IGRhdGV0aW1lLmRhdGUuZnJvbWlzb2Zvcm1hdChjdXIpCiAgICAgICAgICAgICAgICBpZiBjID4gYmFzZTogYmFzZSA9IGMKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogcGFzcwogICAgICAgIG1ldGFbbmFtZV1bImV4cGlyZSJdID0gKGJhc2UgKyBkYXRldGltZS50aW1lZGVsdGEoZGF5cz1kZCkpLmlzb2Zvcm1hdCgpCiAgICAgICAganNhdmUoTUVUQSwgbWV0YSkKICAgIHRyeTogb3MucmVtb3ZlKEJMT0NLICsgIi8iICsgbmFtZSkKICAgIGV4Y2VwdCBFeGNlcHRpb246IHBhc3MKCmRlZiBvbmxpbmVfbWFwKCk6CiAgICBtID0ge30KICAgIGZvciBmIGluIGdsb2IuZ2xvYihPTkxJTkUgKyAiLyoiKToKICAgICAgICBpZmMgPSBvcy5wYXRoLmJhc2VuYW1lKGYpCiAgICAgICAgdHJ5OiB1ID0gb3BlbihmKS5yZWFkKCkuc3BsaXRsaW5lcygpWzBdLnN0cmlwKCkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uOiB1ID0gIiIKICAgICAgICBpZiB1OiBtW3VdID0gaWZjCiAgICByZXR1cm4gbQoKZGVmIGxpdmUoaWZjKToKICAgIGRlZiByZCh4KToKICAgICAgICB0cnk6IHJldHVybiBpbnQob3BlbigiL3N5cy9jbGFzcy9uZXQvJXMvc3RhdGlzdGljcy8lcyIgJSAoaWZjLCB4KSkucmVhZCgpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246IHJldHVybiAwCiAgICByZXR1cm4gcmQoInJ4X2J5dGVzIiksIHJkKCJ0eF9ieXRlcyIpCgpkZWYgZm10KGIpOgogICAgYiA9IGZsb2F0KGIpCiAgICBmb3IgdSBpbiBbIkIiLCJLQiIsIk1CIiwiR0IiLCJUQiJdOgogICAgICAgIGlmIGIgPCAxMDI0OiByZXR1cm4gIiUuMmYgJXMiICUgKGIsIHUpCiAgICAgICAgYiAvPSAxMDI0CiAgICByZXR1cm4gIiUuMmYgUEIiICUgYgoKZGVmIGcyaihneSwgZ20sIGdkKToKICAgIGdkbT1bMCwzMSw1OSw5MCwxMjAsMTUxLDE4MSwyMTIsMjQzLDI3MywzMDQsMzM0XQogICAgaWYgZ3k+MTYwMDogank9OTc5OyBneS09MTYwMAogICAgZWxzZTogank9MDsgZ3ktPTYyMQogICAgZ3kyPWd5KzEgaWYgZ20+MiBlbHNlIGd5CiAgICBkYXlzPTM2NSpneSsoZ3kyKzMpLy80LShneTIrOTkpLy8xMDArKGd5MiszOTkpLy80MDAtODArZ2QrZ2RtW2dtLTFdCiAgICBqeSs9MzMqKGRheXMvLzEyMDUzKTsgZGF5cyU9MTIwNTMKICAgIGp5Kz00KihkYXlzLy8xNDYxKTsgZGF5cyU9MTQ2MQogICAgaWYgZGF5cz4zNjU6IGp5Kz0oZGF5cy0xKS8vMzY1OyBkYXlzPShkYXlzLTEpJTM2NQogICAgaWYgZGF5czwxODY6IGptPTErZGF5cy8vMzE7IGpkPTErZGF5cyUzMQogICAgZWxzZTogam09NysoZGF5cy0xODYpLy8zMDsgamQ9MSsoZGF5cy0xODYpJTMwCiAgICByZXR1cm4ganksam0samQKRkE9WyLZgdix2YjYsdiv24zZhiIsItin2LHYr9uM2KjZh9i02KoiLCLYrtix2K/Yp9ivIiwi2KrbjNixIiwi2YXYsdiv2KfYryIsIti02YfYsduM2YjYsSIsItmF2YfYsSIsItii2KjYp9mGIiwi2KLYsNixIiwi2K/bjCIsItio2YfZhdmGIiwi2KfYs9mB2YbYryJdCmRlZiBqc3RyKGlzbyk6CiAgICB0cnk6CiAgICAgICAgeSxtLGQ9W2ludCh4KSBmb3IgeCBpbiBpc28uc3BsaXQoIi0iKV07IGp5LGptLGpkPWcyaih5LG0sZCkKICAgICAgICByZXR1cm4gIiVkICVzICVkIiUoamQsRkFbam0tMV0sankpCiAgICBleGNlcHQgRXhjZXB0aW9uOiByZXR1cm4gIi0iCmRlZiB0ZWhyYW5fbm93KCk6CiAgICB0PXRpbWUuZ210aW1lKHRpbWUudGltZSgpK2ludCgzLjUqMzYwMCkpOyBqeSxqbSxqZD1nMmoodC50bV95ZWFyLHQudG1fbW9uLHQudG1fbWRheSkKICAgIHJldHVybiAiJWQgJXMgJWQgLSAlMDJkOiUwMmQiJShqZCxGQVtqbS0xXSxqeSx0LnRtX2hvdXIsdC50bV9taW4pCgpDU1MgPSAiIiIKKntib3gtc2l6aW5nOmJvcmRlci1ib3h9Ym9keXtmb250LWZhbWlseTpWYXppcm1hdG4sVGFob21hLHN5c3RlbS11aTttYXJnaW46MDtiYWNrZ3JvdW5kOiMwYjEyMjA7Y29sb3I6I2U2ZWRmNztkaXJlY3Rpb246cnRsfQoud3JhcHttYXgtd2lkdGg6MTE4MHB4O21hcmdpbjowIGF1dG87cGFkZGluZzoyNHB4fQoudG9we2Rpc3BsYXk6ZmxleDtqdXN0aWZ5LWNvbnRlbnQ6c3BhY2UtYmV0d2VlbjthbGlnbi1pdGVtczpjZW50ZXI7ZmxleC13cmFwOndyYXA7Z2FwOjEycHg7bWFyZ2luLWJvdHRvbToxOHB4fQouYnJhbmR7Zm9udC1zaXplOjIycHg7Zm9udC13ZWlnaHQ6ODAwfS5icmFuZCBzcGFue2NvbG9yOiM2MzY2ZjF9Ci5jbG9ja3tiYWNrZ3JvdW5kOiMxMTFhMmU7Ym9yZGVyOjFweCBzb2xpZCAjMjIzMDUyO3BhZGRpbmc6OHB4IDE0cHg7Ym9yZGVyLXJhZGl1czoxMHB4O2ZvbnQtc2l6ZToxM3B4O2NvbG9yOiM5ZmIwY2N9Ci5jYXJkc3tkaXNwbGF5OmZsZXg7Z2FwOjEycHg7ZmxleC13cmFwOndyYXA7bWFyZ2luLWJvdHRvbToxOHB4fQouY2FyZHtmbGV4OjE7bWluLXdpZHRoOjE1MHB4O2JhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDEzNWRlZywjMTUxZjM4LCMxMTFhMmUpO2JvcmRlcjoxcHggc29saWQgIzIyMzA1Mjtib3JkZXItcmFkaXVzOjE0cHg7cGFkZGluZzoxNHB4IDE2cHh9Ci5jYXJkIC5re2NvbG9yOiM4ZWExYzA7Zm9udC1zaXplOjEycHh9LmNhcmQgLnZ7Zm9udC1zaXplOjIwcHg7Zm9udC13ZWlnaHQ6NzAwO21hcmdpbi10b3A6NHB4fQoucGFuZWx7YmFja2dyb3VuZDojMTExYTJlO2JvcmRlcjoxcHggc29saWQgIzIyMzA1Mjtib3JkZXItcmFkaXVzOjE0cHg7cGFkZGluZzoxNnB4O21hcmdpbi1ib3R0b206MThweH0KLnBhbmVsIGgze21hcmdpbjowIDAgMTJweDtmb250LXNpemU6MTVweDtjb2xvcjojYzdkM2U4fQpmb3JtLmFkZHtkaXNwbGF5OmZsZXg7Z2FwOjEwcHg7ZmxleC13cmFwOndyYXA7YWxpZ24taXRlbXM6ZW5kfQpsYWJlbHtkaXNwbGF5OmJsb2NrO2ZvbnQtc2l6ZToxMnB4O2NvbG9yOiM4ZWExYzA7bWFyZ2luLWJvdHRvbTo1cHh9CmlucHV0e3BhZGRpbmc6OXB4IDExcHg7Ym9yZGVyLXJhZGl1czo5cHg7Ym9yZGVyOjFweCBzb2xpZCAjMmEzYTVlO2JhY2tncm91bmQ6IzBiMTIyMDtjb2xvcjojZTZlZGY3O2ZvbnQtZmFtaWx5OmluaGVyaXQ7bWluLXdpZHRoOjEyMHB4fQouYnRue2JvcmRlcjowO2JvcmRlci1yYWRpdXM6OXB4O3BhZGRpbmc6MTBweCAxOHB4O2N1cnNvcjpwb2ludGVyO2ZvbnQtZmFtaWx5OmluaGVyaXQ7Zm9udC13ZWlnaHQ6NzAwO2NvbG9yOiNmZmZ9Ci5idG4uZ3tiYWNrZ3JvdW5kOiMxNmEzNGF9LmJ0bi5ye2JhY2tncm91bmQ6I2RjMjYyNn0uYnRuLmJ7YmFja2dyb3VuZDojNjM2NmYxfS5idG4ueXtiYWNrZ3JvdW5kOiNkOTc3MDZ9LmJ0bi5ze3BhZGRpbmc6NXB4IDlweDtmb250LXNpemU6MTJweDtmb250LXdlaWdodDo2MDB9CnRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyLWNvbGxhcHNlOmNvbGxhcHNlO2JhY2tncm91bmQ6IzExMWEyZTtib3JkZXI6MXB4IHNvbGlkICMyMjMwNTI7Ym9yZGVyLXJhZGl1czoxNHB4O292ZXJmbG93OmhpZGRlbn0KdGgsdGR7cGFkZGluZzoxMHB4IDEycHg7dGV4dC1hbGlnbjpyaWdodDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjMWMyYTQ4O2ZvbnQtc2l6ZToxM3B4O3doaXRlLXNwYWNlOm5vd3JhcH0KdGh7YmFja2dyb3VuZDojMTYyMjNkO2NvbG9yOiM5ZmIwY2M7Zm9udC13ZWlnaHQ6NzAwfQp0cjpob3ZlciB0ZHtiYWNrZ3JvdW5kOiMxNDFmMzh9Ci5vbntjb2xvcjojMjJjNTVlO2ZvbnQtd2VpZ2h0OjcwMH0ub2Zme2NvbG9yOiM2NDc0OGJ9Ci5iYXJ7aGVpZ2h0OjdweDtiYWNrZ3JvdW5kOiMyMjMwNGY7Ym9yZGVyLXJhZGl1czo2cHg7b3ZlcmZsb3c6aGlkZGVuO21hcmdpbi10b3A6NXB4O21pbi13aWR0aDoxMDBweH0KLmJhcj5pe2Rpc3BsYXk6YmxvY2s7aGVpZ2h0OjEwMCU7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoOTBkZWcsIzIyYzU1ZSwjZWFiMzA4LCNlZjQ0NDQpfQoubW9ub3tmb250LWZhbWlseTp1aS1tb25vc3BhY2UsTWVubG8sbW9ub3NwYWNlO2RpcmVjdGlvbjpsdHI7ZGlzcGxheTppbmxpbmUtYmxvY2t9Ci5hY3Rze2Rpc3BsYXk6ZmxleDtnYXA6NnB4fS5vdmVye2NvbG9yOiNlZjQ0NDQ7Zm9udC13ZWlnaHQ6NzAwfQoiIiIKCkxPR0lOID0gIiIiPCFkb2N0eXBlIGh0bWw+PGh0bWwgbGFuZz1mYSBkaXI9cnRsPjxtZXRhIGNoYXJzZXQ9dXRmLTg+CjxtZXRhIG5hbWU9dmlld3BvcnQgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLGluaXRpYWwtc2NhbGU9MSI+PHRpdGxlPtmI2LHZiNivINio2Ycg2b7ZhtmEPC90aXRsZT4KPGxpbmsgaHJlZj0iaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL3Jhc3Rpa2VyZGFyL3ZhemlybWF0bkB2MzMuMDAzL1ZhemlybWF0bi1mb250LWZhY2UuY3NzIiByZWw9c3R5bGVzaGVldD4KPHN0eWxlPiVzCi5sZ3ttaW4taGVpZ2h0OjEwMHZoO2Rpc3BsYXk6ZmxleDthbGlnbi1pdGVtczpjZW50ZXI7anVzdGlmeS1jb250ZW50OmNlbnRlcjtiYWNrZ3JvdW5kOnJhZGlhbC1ncmFkaWVudCgxMjAwcHggNjAwcHggYXQgNTAlJSAtMTAlJSwjMWUyYTRhLCMwYjEyMjApfQouYm94e3dpZHRoOjM0MHB4O2JhY2tncm91bmQ6IzExMWEyZTtib3JkZXI6MXB4IHNvbGlkICMyMjMwNTI7Ym9yZGVyLXJhZGl1czoxOHB4O3BhZGRpbmc6MjhweDtib3gtc2hhZG93OjAgMjBweCA2MHB4IHJnYmEoMCwwLDAsLjQ1KX0KLmJveCBoMXtmb250LXNpemU6MjBweDttYXJnaW46MCAwIDRweDt0ZXh0LWFsaWduOmNlbnRlcn0uYm94IHB7Y29sb3I6IzhlYTFjMDtmb250LXNpemU6MTNweDt0ZXh0LWFsaWduOmNlbnRlcjttYXJnaW46MCAwIDIwcHh9Ci5ib3ggaW5wdXR7d2lkdGg6MTAwJSU7bWFyZ2luLWJvdHRvbToxNHB4fS5ib3ggLmJ0bnt3aWR0aDoxMDAlJX0KLmVycntiYWNrZ3JvdW5kOiMzYjEyMjA7Ym9yZGVyOjFweCBzb2xpZCAjN2YxZDFkO2NvbG9yOiNmY2E1YTU7cGFkZGluZzo4cHg7Ym9yZGVyLXJhZGl1czo5cHg7Zm9udC1zaXplOjEzcHg7dGV4dC1hbGlnbjpjZW50ZXI7bWFyZ2luLWJvdHRvbToxNHB4fQoubG9nb3t3aWR0aDo1NHB4O2hlaWdodDo1NHB4O21hcmdpbjowIGF1dG8gMTJweDtib3JkZXItcmFkaXVzOjE0cHg7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCM2MzY2ZjEsIzIyYzU1ZSk7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRlcjtqdXN0aWZ5LWNvbnRlbnQ6Y2VudGVyO2ZvbnQtc2l6ZToyNnB4fTwvc3R5bGU+CjxkaXYgY2xhc3M9bGc+PGZvcm0gY2xhc3M9Ym94IG1ldGhvZD1wb3N0IGFjdGlvbj0vbG9naW4+CjxkaXYgY2xhc3M9bG9nbz7wn5SSPC9kaXY+PGgxPtm+2YbZhCDZhdiv24zYsduM2KogVlBOPC9oMT48cD5MMlRQIC8gSVBzZWM8L3A+CiVzCjxsYWJlbD7Zhtin2YUg2qnYp9ix2KjYsduMPC9sYWJlbD48aW5wdXQgbmFtZT11IGF1dG9mb2N1cyByZXF1aXJlZD4KPGxhYmVsPtix2YXYsiDYudio2YjYsTwvbGFiZWw+PGlucHV0IG5hbWU9cCB0eXBlPXBhc3N3b3JkIHJlcXVpcmVkPgo8YnV0dG9uIGNsYXNzPSJidG4gYiI+2YjYsdmI2K88L2J1dHRvbj48L2Zvcm0+PC9kaXY+PC9odG1sPiIiIgoKZGVmIHBhZ2UoYm9keSk6CiAgICByZXR1cm4gKCI8IWRvY3R5cGUgaHRtbD48aHRtbCBsYW5nPWZhIGRpcj1ydGw+PG1ldGEgY2hhcnNldD11dGYtOD4iCiAgICAgICAgIjxtZXRhIG5hbWU9dmlld3BvcnQgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCxpbml0aWFsLXNjYWxlPTFcIj48dGl0bGU+2b7ZhtmEIFZQTjwvdGl0bGU+IgogICAgICAgICI8bGluayBocmVmPVwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL3Jhc3Rpa2VyZGFyL3ZhemlybWF0bkB2MzMuMDAzL1ZhemlybWF0bi1mb250LWZhY2UuY3NzXCIgcmVsPXN0eWxlc2hlZXQ+IgogICAgICAgICI8c3R5bGU+IitDU1MrIjwvc3R5bGU+PGRpdiBjbGFzcz13cmFwPiIrYm9keSsiPC9kaXY+IgogICAgICAgICI8c2NyaXB0PnNldFRpbWVvdXQoZnVuY3Rpb24oKXtsb2NhdGlvbi5yZWxvYWQoKX0sMTUwMDApPC9zY3JpcHQ+PC9odG1sPiIpCgpjbGFzcyBIKEJhc2VIVFRQUmVxdWVzdEhhbmRsZXIpOgogICAgZGVmIHRvayhzZWxmKToKICAgICAgICBtID0gcmUuc2VhcmNoKHInc2lkPShbQS1aYS16MC05Xy1dKyknLCBzZWxmLmhlYWRlcnMuZ2V0KCJDb29raWUiLCIiKSkKICAgICAgICByZXR1cm4gbS5ncm91cCgxKSBpZiBtIGVsc2UgTm9uZQogICAgZGVmIGF1dGhlZChzZWxmKToKICAgICAgICB0PXNlbGYudG9rKCk7IHJldHVybiB0IGFuZCBTRVNTSU9OUy5nZXQodCwwKT50aW1lLnRpbWUoKQogICAgZGVmIHJkaXIoc2VsZiwgbG9jLCBjb29raWU9Tm9uZSk6CiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKDMwMyk7IHNlbGYuc2VuZF9oZWFkZXIoIkxvY2F0aW9uIixsb2MpCiAgICAgICAgaWYgY29va2llOiBzZWxmLnNlbmRfaGVhZGVyKCJTZXQtQ29va2llIixjb29raWUpCiAgICAgICAgc2VsZi5lbmRfaGVhZGVycygpCiAgICBkZWYgb3V0KHNlbGYsIHMsIGNvZGU9MjAwKToKICAgICAgICBiPXMuZW5jb2RlKCJ1dGYtOCIpOyBzZWxmLnNlbmRfcmVzcG9uc2UoY29kZSkKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LVR5cGUiLCJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiKTsgc2VsZi5lbmRfaGVhZGVycygpOyBzZWxmLndmaWxlLndyaXRlKGIpCiAgICBkZWYgZG9fUE9TVChzZWxmKToKICAgICAgICBsbj1pbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiLDApKQogICAgICAgIHE9dXJsbGliLnBhcnNlLnBhcnNlX3FzKHNlbGYucmZpbGUucmVhZChsbikuZGVjb2RlKCkpOyBnPWxhbWJkYSBrOnEuZ2V0KGssWyIiXSlbMF0KICAgICAgICBpZiBzZWxmLnBhdGg9PSIvbG9naW4iOgogICAgICAgICAgICBpZiBnKCJ1Iik9PUFETUlOX1VTRVIgYW5kIGcoInAiKT09QURNSU5fUEFTUzoKICAgICAgICAgICAgICAgIHRrPXNlY3JldHMudG9rZW5fdXJsc2FmZSgyNCk7IFNFU1NJT05TW3RrXT10aW1lLnRpbWUoKSs4KjM2MDAKICAgICAgICAgICAgICAgIHJldHVybiBzZWxmLnJkaXIoIi8iLCJzaWQ9JXM7IEh0dHBPbmx5OyBQYXRoPS87IE1heC1BZ2U9Mjg4MDA7IFNlY3VyZTsgU2FtZVNpdGU9TGF4IiV0aykKICAgICAgICAgICAgcmV0dXJuIHNlbGYub3V0KExPR0lOJShDU1MsIjxkaXYgY2xhc3M9ZXJyPtmG2KfZhSDaqdin2LHYqNix24wg24zYpyDYsdmF2LIg2KfYtNiq2KjYp9mHINin2LPYqjwvZGl2PiIpLDQwMSkKICAgICAgICBpZiBub3Qgc2VsZi5hdXRoZWQoKTogcmV0dXJuIHNlbGYucmRpcigiL2xvZ2luIikKICAgICAgICBpZiBzZWxmLnBhdGg9PSIvYWRkIjogYWRkX3VzZXIoZygidSIpLGcoInAiKSxnKCJxIikgb3IgIjIwIixnKCJkIikgb3IgIjAiKQogICAgICAgIGVsaWYgc2VsZi5wYXRoPT0iL2RlbCI6IGRlbF91c2VyKGcoInUiKSkKICAgICAgICBlbGlmIHNlbGYucGF0aD09Ii9yZXNldCI6IHJlc2V0X3VzYWdlKGcoInUiKSkKICAgICAgICBlbGlmIHNlbGYucGF0aD09Ii9yZW5ldyI6IHJlbmV3KGcoInUiKSxnKCJkIikgb3IgIjMwIikKICAgICAgICByZXR1cm4gc2VsZi5yZGlyKCIvIikKICAgIGRlZiBkb19HRVQoc2VsZik6CiAgICAgICAgaWYgc2VsZi5wYXRoPT0iL2xvZ2luIjoKICAgICAgICAgICAgaWYgc2VsZi5hdXRoZWQoKTogcmV0dXJuIHNlbGYucmRpcigiLyIpCiAgICAgICAgICAgIHJldHVybiBzZWxmLm91dChMT0dJTiUoQ1NTLCIiKSkKICAgICAgICBpZiBzZWxmLnBhdGg9PSIvbG9nb3V0IjoKICAgICAgICAgICAgdD1zZWxmLnRvaygpCiAgICAgICAgICAgIGlmIHQ6IFNFU1NJT05TLnBvcCh0LE5vbmUpCiAgICAgICAgICAgIHJldHVybiBzZWxmLnJkaXIoIi9sb2dpbiIsInNpZD07IFBhdGg9LzsgTWF4LUFnZT0wIikKICAgICAgICBpZiBub3Qgc2VsZi5hdXRoZWQoKTogcmV0dXJuIHNlbGYucmRpcigiL2xvZ2luIikKICAgICAgICB1c2FnZT1qbG9hZChTVE9SRSk7IG1ldGE9amxvYWQoTUVUQSk7IG9tPW9ubGluZV9tYXAoKQogICAgICAgIHVzZXJzPWxpc3RfdXNlcnMoKTsgcHdtYXA9ZGljdCh1c2VycykKICAgICAgICBuYW1lcz1zb3J0ZWQoc2V0KFt1IGZvciB1LF8gaW4gdXNlcnNdK2xpc3QobWV0YS5rZXlzKCkpKSxrZXk9bGFtYmRhIHg6KGxlbih4KSx4KSkKICAgICAgICB0b2RheT1kYXRldGltZS5kYXRlLnRvZGF5KCkKICAgICAgICByb3dzPSIiOyB0b3RfdT10b3RfZD0wOyBuX29uPTAKICAgICAgICBmb3IgaSx1IGluIGVudW1lcmF0ZShuYW1lcywxKToKICAgICAgICAgICAgYmFzZT11c2FnZS5nZXQodSx7InJ4IjowLCJ0eCI6MH0pOyB1cD1iYXNlLmdldCgicngiLDApOyBkbj1iYXNlLmdldCgidHgiLDApCiAgICAgICAgICAgIG9uPXUgaW4gb20KICAgICAgICAgICAgaWYgb246CiAgICAgICAgICAgICAgICBsdSxsZD1saXZlKG9tW3VdKTsgdXArPWx1OyBkbis9bGQ7IG5fb24rPTEKICAgICAgICAgICAgdG90X3UrPXVwOyB0b3RfZCs9ZG47IHRvdGFsPXVwK2RuCiAgICAgICAgICAgIGluZm89bWV0YS5nZXQodSx7fSk7IHF1b3RhPWluZm8uZ2V0KCJxdW90YSIsMCk7IGV4cGlyZT1pbmZvLmdldCgiZXhwaXJlIiwiIikKICAgICAgICAgICAgY3JlYXRlZD1qc3RyKGluZm8uZ2V0KCJjcmVhdGVkIiwiIikpCiAgICAgICAgICAgIHFnYj1xdW90YS9HQiBpZiBxdW90YSBlbHNlIDAKICAgICAgICAgICAgcGN0PW1pbigxMDAsaW50KHRvdGFsKjEwMC9xdW90YSkpIGlmIHF1b3RhIGVsc2UgMAogICAgICAgICAgICBvdmVyX3E9cXVvdGEgYW5kIHRvdGFsPj1xdW90YQogICAgICAgICAgICBleHBpcmVkPUZhbHNlOyBleHBfdHh0PSLZhtin2YXYrdiv2YjYryIKICAgICAgICAgICAgaWYgZXhwaXJlOgogICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIGVkPWRhdGV0aW1lLmRhdGUuZnJvbWlzb2Zvcm1hdChleHBpcmUpOyByZW1fZD0oZWQtdG9kYXkpLmRheXMKICAgICAgICAgICAgICAgICAgICBleHBpcmVkPXJlbV9kPDAKICAgICAgICAgICAgICAgICAgICBleHBfdHh0PSgiPHNwYW4gY2xhc3M9b3Zlcj7ZhdmG2YLYttuMPC9zcGFuPiIgaWYgZXhwaXJlZCBlbHNlICIlcyAoJWQg2LHZiNiyKSIlKGpzdHIoZXhwaXJlKSxyZW1fZCkpCiAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOiBwYXNzCiAgICAgICAgICAgIHN0YXR1cz0iPHNwYW4gY2xhc3M9b24+4pePINii2YbZhNin24zZhjwvc3Bhbj4iIGlmIG9uIGVsc2UgIjxzcGFuIGNsYXNzPW9mZj7YotmB2YTYp9uM2YY8L3NwYW4+IgogICAgICAgICAgICB1c2VkY2VsbD0oIjxzcGFuIGNsYXNzPW92ZXI+JXM8L3NwYW4+IiVmbXQodG90YWwpKSBpZiBvdmVyX3EgZWxzZSBmbXQodG90YWwpCiAgICAgICAgICAgIGJhcj0iPGRpdiBjbGFzcz1iYXI+PGkgc3R5bGU9d2lkdGg6JWQlJT48L2k+PC9kaXY+IiVwY3QKICAgICAgICAgICAgcmVtPW1heChxdW90YS10b3RhbCwwKQogICAgICAgICAgICBhY3RzPSgiPGRpdiBjbGFzcz1hY3RzPiIKICAgICAgICAgICAgICAgICI8Zm9ybSBtZXRob2Q9cG9zdCBhY3Rpb249L3JlbmV3PjxpbnB1dCB0eXBlPWhpZGRlbiBuYW1lPXUgdmFsdWU9XCIlc1wiPjxpbnB1dCB0eXBlPWhpZGRlbiBuYW1lPWQgdmFsdWU9MzA+PGJ1dHRvbiBjbGFzcz1cImJ0biBzIHlcIj4r27PbsCDYsdmI2LI8L2J1dHRvbj48L2Zvcm0+IgogICAgICAgICAgICAgICAgIjxmb3JtIG1ldGhvZD1wb3N0IGFjdGlvbj0vcmVzZXQgb25zdWJtaXQ9XCJyZXR1cm4gY29uZmlybSgn2LXZgdixINqp2LHYr9mGINmF2LXYsdmBICVz2J8nKVwiPjxpbnB1dCB0eXBlPWhpZGRlbiBuYW1lPXUgdmFsdWU9XCIlc1wiPjxidXR0b24gY2xhc3M9XCJidG4gcyBiXCI+2LXZgdixPC9idXR0b24+PC9mb3JtPiIKICAgICAgICAgICAgICAgICI8Zm9ybSBtZXRob2Q9cG9zdCBhY3Rpb249L2RlbCBvbnN1Ym1pdD1cInJldHVybiBjb25maXJtKCfYrdiw2YEg2qnYp9ix2KjYsSAlc9ifJylcIj48aW5wdXQgdHlwZT1oaWRkZW4gbmFtZT11IHZhbHVlPVwiJXNcIj48YnV0dG9uIGNsYXNzPVwiYnRuIHMgclwiPtit2LDZgTwvYnV0dG9uPjwvZm9ybT4iCiAgICAgICAgICAgICAgICAiPC9kaXY+IiklKHUsdSx1LHUsdSkKICAgICAgICAgICAgcm93cys9KCI8dHI+PHRkPiVkPC90ZD48dGQgY2xhc3M9bW9ubz4lczwvdGQ+PHRkIGNsYXNzPW1vbm8+JXM8L3RkPjx0ZD4lczwvdGQ+PHRkPiVzPC90ZD4iCiAgICAgICAgICAgICAgICAgICAiPHRkPiVzPC90ZD48dGQ+JXMg2q/bjNqvPC90ZD48dGQ+JXMlczwvdGQ+PHRkPiVzPC90ZD48dGQ+JXM8L3RkPjwvdHI+IiklKAogICAgICAgICAgICAgICAgaSx1LHB3bWFwLmdldCh1LCIiKSxzdGF0dXMsY3JlYXRlZCxleHBfdHh0LAogICAgICAgICAgICAgICAgKCgiJS4wZiIlcWdiKSBpZiBxZ2I9PWludChxZ2IpIGVsc2UgKCIlLjFmIiVxZ2IpKSwKICAgICAgICAgICAgICAgIHVzZWRjZWxsLGJhcixmbXQocmVtKSxhY3RzKQogICAgICAgIGNhcmRzPSgiPGRpdiBjbGFzcz1jYXJkcz4iCiAgICAgICAgICAgICI8ZGl2IGNsYXNzPWNhcmQ+PGRpdiBjbGFzcz1rPtqp2YQg2qnYp9ix2KjYsdin2YY8L2Rpdj48ZGl2IGNsYXNzPXY+JWQ8L2Rpdj48L2Rpdj4iCiAgICAgICAgICAgICI8ZGl2IGNsYXNzPWNhcmQ+PGRpdiBjbGFzcz1rPtii2YbZhNin24zZhjwvZGl2PjxkaXYgY2xhc3M9diBzdHlsZT1jb2xvcjojMjJjNTVlPiVkPC9kaXY+PC9kaXY+IgogICAgICAgICAgICAiPGRpdiBjbGFzcz1jYXJkPjxkaXYgY2xhc3M9az7Zhdis2YXZiNi5INiv2KfZhtmE2YjYrzwvZGl2PjxkaXYgY2xhc3M9dj4lczwvZGl2PjwvZGl2PiIKICAgICAgICAgICAgIjxkaXYgY2xhc3M9Y2FyZD48ZGl2IGNsYXNzPWs+2YXYrNmF2YjYuSDYotm+2YTZiNivPC9kaXY+PGRpdiBjbGFzcz12PiVzPC9kaXY+PC9kaXY+PC9kaXY+IiklKAogICAgICAgICAgICBsZW4obmFtZXMpLG5fb24sZm10KHRvdF9kKSxmbXQodG90X3UpKQogICAgICAgIGFkZGY9KCI8ZGl2IGNsYXNzPXBhbmVsPjxoMz7inpUg2KfZgdiy2YjYr9mGINqp2KfYsdio2LEg2KzYr9uM2K88L2gzPjxmb3JtIGNsYXNzPWFkZCBtZXRob2Q9cG9zdCBhY3Rpb249L2FkZD4iCiAgICAgICAgICAgICI8ZGl2PjxsYWJlbD7Zhtin2YUg2qnYp9ix2KjYsduMPC9sYWJlbD48aW5wdXQgbmFtZT11IHJlcXVpcmVkPjwvZGl2PiIKICAgICAgICAgICAgIjxkaXY+PGxhYmVsPtix2YXYsiDYudio2YjYsTwvbGFiZWw+PGlucHV0IG5hbWU9cCByZXF1aXJlZD48L2Rpdj4iCiAgICAgICAgICAgICI8ZGl2PjxsYWJlbD7Ys9mH2YXbjNmHICjar9uM2q/Yp9io2KfbjNiqKTwvbGFiZWw+PGlucHV0IG5hbWU9cSB0eXBlPW51bWJlciBzdGVwPTAuNSB2YWx1ZT0yMCByZXF1aXJlZD48L2Rpdj4iCiAgICAgICAgICAgICI8ZGl2PjxsYWJlbD7Zhdiv2KogKNix2YjYsikg4oCUINuwID0g2YbYp9mF2K3Yr9mI2K88L2xhYmVsPjxpbnB1dCBuYW1lPWQgdHlwZT1udW1iZXIgdmFsdWU9MzAgcmVxdWlyZWQ+PC9kaXY+IgogICAgICAgICAgICAiPGJ1dHRvbiBjbGFzcz1cImJ0biBnXCI+2KfZgdiy2YjYr9mGPC9idXR0b24+PC9mb3JtPjwvZGl2PiIpCiAgICAgICAgaGVhZD0oIjxkaXYgY2xhc3M9dG9wPjxkaXYgY2xhc3M9YnJhbmQ+2b7ZhtmEINmF2K/bjNix24zYqiA8c3Bhbj5WUE48L3NwYW4+PC9kaXY+IgogICAgICAgICAgICAiPGRpdiBzdHlsZT1kaXNwbGF5OmZsZXg7Z2FwOjEwcHg7YWxpZ24taXRlbXM6Y2VudGVyPiIKICAgICAgICAgICAgIjxkaXYgY2xhc3M9Y2xvY2s+8J+XkyAlczwvZGl2PjxhIGhyZWY9L2xvZ291dCBjbGFzcz1cImJ0biByIHNcIiBzdHlsZT10ZXh0LWRlY29yYXRpb246bm9uZT7Yrtix2YjYrDwvYT48L2Rpdj48L2Rpdj4iKSV0ZWhyYW5fbm93KCkKICAgICAgICB0YWJsZT0oIjx0YWJsZT48dHI+PHRoPiM8L3RoPjx0aD7aqdin2LHYqNixPC90aD48dGg+2LHZhdiyPC90aD48dGg+2YjYtti524zYqjwvdGg+PHRoPtiq2KfYsduM2K4g2LPYp9iu2Ko8L3RoPjx0aD7Yp9mG2YLYttinPC90aD4iCiAgICAgICAgICAgICI8dGg+2LPZh9mF24zZhzwvdGg+PHRoPtmF2LXYsdmB4oCM2LTYr9mHPC90aD48dGg+2YbZhdmI2K/Yp9ixPC90aD48dGg+2KjYp9mC24zigIzZhdin2YbYr9mHPC90aD48dGg+2LnZhdmE24zYp9iqPC90aD48L3RyPiIrcm93cysiPC90YWJsZT4iKQogICAgICAgIHNlbGYub3V0KHBhZ2UoaGVhZCtjYXJkcythZGRmK3RhYmxlKSkKICAgIGRlZiBsb2dfbWVzc2FnZShzZWxmLCphKTogcGFzcwoKaWYgX19uYW1lX189PSJfX21haW5fXyI6CiAgICBIVFRQU2VydmVyKCgiMTI3LjAuMC4xIiw4MDg4KSxIKS5zZXJ2ZV9mb3JldmVyKCkK" | base64 -d > /usr/local/bin/vpn-panel.py
echo "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwojIEVuZm9yY2UgcGVyLXVzZXIgZGF0YSBxdW90YSBBTkQgdGltZSBleHBpcnk6IGRpc2Nvbm5lY3QgJiBibG9jayB2aW9sYXRvcnMuCmltcG9ydCBqc29uLCBvcywgZ2xvYiwgdGltZSwgc2lnbmFsLCBkYXRldGltZQoKTUVUQT0iL3Zhci9saWIvdnBuc3RhdC9tZXRhLmpzb24iOyBVU0FHRT0iL3Zhci9saWIvdnBuc3RhdC91c2FnZS5qc29uIgpPTkxJTkU9Ii9ydW4vdnBuLW9ubGluZSI7IEJMT0NLPSIvcnVuL3Zwbi1ibG9ja2VkIgoKZGVmIGpsb2FkKHApOgogICAgdHJ5OiByZXR1cm4ganNvbi5sb2FkKG9wZW4ocCkpCiAgICBleGNlcHQgRXhjZXB0aW9uOiByZXR1cm4ge30KZGVmIGxpdmUoaWZjKToKICAgIGRlZiByZCh4KToKICAgICAgICB0cnk6IHJldHVybiBpbnQob3BlbigiL3N5cy9jbGFzcy9uZXQvJXMvc3RhdGlzdGljcy8lcyIlKGlmYyx4KSkucmVhZCgpKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246IHJldHVybiAwCiAgICByZXR1cm4gcmQoInJ4X2J5dGVzIikrcmQoInR4X2J5dGVzIikKZGVmIG9ubGluZV9tYXAoKToKICAgIG09e30KICAgIGZvciBmIGluIGdsb2IuZ2xvYihPTkxJTkUrIi8qIik6CiAgICAgICAgaWZjPW9zLnBhdGguYmFzZW5hbWUoZikKICAgICAgICB0cnk6CiAgICAgICAgICAgIGxzPW9wZW4oZikucmVhZCgpLnNwbGl0bGluZXMoKTsgdT1sc1swXS5zdHJpcCgpOyBwaWQ9aW50KGxzWzFdLnNwbGl0KClbMV0pCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogY29udGludWUKICAgICAgICBtW3VdPShpZmMscGlkKQogICAgcmV0dXJuIG0KCm9zLm1ha2VkaXJzKEJMT0NLLGV4aXN0X29rPVRydWUpCndoaWxlIFRydWU6CiAgICBtZXRhPWpsb2FkKE1FVEEpOyB1c2FnZT1qbG9hZChVU0FHRSk7IG9tPW9ubGluZV9tYXAoKQogICAgdG9kYXk9ZGF0ZXRpbWUuZGF0ZS50b2RheSgpCiAgICB1c2Vycz1zZXQobGlzdChtZXRhLmtleXMoKSkrbGlzdCh1c2FnZS5rZXlzKCkpK2xpc3Qob20ua2V5cygpKSkKICAgIGZvciB1IGluIHVzZXJzOgogICAgICAgIGluZm89bWV0YS5nZXQodSx7fSk7IHF1b3RhPWluZm8uZ2V0KCJxdW90YSIsMCk7IGV4cGlyZT1pbmZvLmdldCgiZXhwaXJlIiwiIikKICAgICAgICBiYXNlPXVzYWdlLmdldCh1LHsicngiOjAsInR4IjowfSk7IHRvdGFsPWJhc2UuZ2V0KCJyeCIsMCkrYmFzZS5nZXQoInR4IiwwKQogICAgICAgIGlmIHUgaW4gb206IHRvdGFsKz1saXZlKG9tW3VdWzBdKQogICAgICAgIG92ZXJfcXVvdGEgPSBib29sKHF1b3RhKSBhbmQgdG90YWw+PXF1b3RhCiAgICAgICAgZXhwaXJlZD1GYWxzZQogICAgICAgIGlmIGV4cGlyZToKICAgICAgICAgICAgdHJ5OiBleHBpcmVkPWRhdGV0aW1lLmRhdGUuZnJvbWlzb2Zvcm1hdChleHBpcmUpPHRvZGF5CiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246IGV4cGlyZWQ9RmFsc2UKICAgICAgICB2aW9sYXRlPW92ZXJfcXVvdGEgb3IgZXhwaXJlZAogICAgICAgIGJsb2NrZWQ9b3MucGF0aC5leGlzdHMoQkxPQ0srIi8iK3UpCiAgICAgICAgaWYgdmlvbGF0ZToKICAgICAgICAgICAgaWYgdSBpbiBvbToKICAgICAgICAgICAgICAgIHRyeTogb3Mua2lsbChvbVt1XVsxXSxzaWduYWwuU0lHVEVSTSkKICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246IHBhc3MKICAgICAgICAgICAgaWYgbm90IGJsb2NrZWQ6IG9wZW4oQkxPQ0srIi8iK3UsInciKS53cml0ZShzdHIoaW50KHRpbWUudGltZSgpKSkpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgaWYgYmxvY2tlZDoKICAgICAgICAgICAgICAgIHRyeTogb3MucmVtb3ZlKEJMT0NLKyIvIit1KQogICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogcGFzcwogICAgdGltZS5zbGVlcCgyMCkK" | base64 -d > /usr/local/bin/vpn-enforce.py
python3 - "$PANEL_USER" "$PANEL_PASS" "$PANEL_PORT" <<'PY'
import sys
u,p,port=sys.argv[1],sys.argv[2],sys.argv[3]
s=open("/usr/local/bin/vpn-panel.py").read()
s=s.replace("__PANEL_USER__",u).replace("__PANEL_PASS__",p)
s=s.replace('("127.0.0.1",8088)','("127.0.0.1",%s)'%port)
open("/usr/local/bin/vpn-panel.py","w").write(s)
PY
chmod +x /usr/local/bin/vpn-panel.py /usr/local/bin/vpn-enforce.py

cat > /etc/systemd/system/vpn-panel.service <<EOF
[Unit]
Description=VPN Web Panel
After=network.target
[Service]
ExecStart=/usr/bin/python3 /usr/local/bin/vpn-panel.py
Restart=always
User=root
[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/vpn-enforce.service <<EOF
[Unit]
Description=VPN quota/time enforcement
After=network.target
[Service]
ExecStart=/usr/bin/python3 /usr/local/bin/vpn-enforce.py
Restart=always
User=root
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now vpn-panel vpn-enforce >/dev/null 2>&1

echo ">> پیکربندی nginx + SSL..."
cat > /etc/nginx/sites-available/vpnpanel <<EOF
server {
    listen 80;
    server_name ${DOMAIN};
    location / {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
EOF
ln -sf /etc/nginx/sites-available/vpnpanel /etc/nginx/sites-enabled/vpnpanel
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL" --redirect || \
  echo "!! دریافت SSL ناموفق بود؛ دامنه باید به این سرور اشاره کند و پورت 80/443 باز باشد."

echo ""
echo "==================================================="
echo "  ✅ نصب کامل شد"
echo "  پنل : https://$DOMAIN"
echo "  ورود: $PANEL_USER"
echo "  PSK : $VPN_PSK"
echo "  پورت‌های UDP 500/4500 و TCP 80/443 را در فایروال باز کنید."
echo "==================================================="
